# These are supported funding model platforms

github : # replace mistakes and even fix them ["https://github.com/RAFhub6/some-stuff/discussions"]
discord : # talk about mistakes and failiures/issues ["https://discord.gg/qz9bM3M"]
repl.it : # make projects proving i made a mistake ["https://replit.com/teams/join/joqtkszalabyahcftnzzzlvlddrdddzi-thepurest"]
scratch : # make proof about what i made a mistake or issue ["https://scratch.mit.edu/users/NewRAF/"]
youtube : # make videos about what happend in the issues ["https://www.youtube.com/channel/UCcpiVC3B1Za0ph8Qfhgkvgw"]
