# These are supported funding model platforms

github : # replace mistakes and even fix them
discord : # talk about mistakes and failiures/issues
repl.it : # make projects proving i made a mistake
scratch : # make proof about what i made a mistake or issue
youtube : # make videos about what happend in the issues
